# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# output path
/Inputs/root_output /home/ilker/Projects/UTATPC/output/Co60_3cmv2.root
 
# make unstable isotopes decay at t=0
/Inputs/decay_at_time_zero true  # this is set to false by default


/random/setSeeds 0 32

# particle type

/gps/particle e-


# spherical volume source
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/centre 0. 0. 5. cm
/gps/pos/radius 0.01 mm

# energy distribution
/gps/ene/mono 0.5 MeV

