# This is a comment and will be ignored by geant4

# The detector configuration (false  VD or true HD)
/geometry/use_hd_detector_configuration true

# World volume dimensions in meters. Place this config before run initialization
# For hd detector geometry

/geometry/world_width  134.
/geometry/world_height 20.
/geometry/world_length 4.

#/geometry/world_width  150.
#/geometry/world_height 150.
#/geometry/world_length 150.

# initialize run
/random/setSeeds 3981 31
/run/initialize

# print photons from neutron capture. 0: false 1:true
/neutron/get_photons 1

# set verbosity
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

# output path
/inputs/output_file ../output/neutron.root

# limit radioactive decay chains
# use if needed
#/grdm/nucleusLimits 1 35 1 17  # aMin aMax zMin zMax

/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/do_not_adjust_final_state false
/process/had/particle_hp/skip_missing_isotopes false

/process/inactivate hadElastic
/process/inactivate neutronInelastic
/process/inactivate nFission

################################################################################
## Source Definition
################################################################################

## Energy Distribution
## Spectrum from Guilherme Ruiz Ferreira
## Email: guilherme.ruizferreira@postgrad.manchester.ac.uk
## Total neutron rates considering one DUNE cave (2 in total) with dimensions of 145mx20mx28m
## Total fluence of 277 neutrons/second
## Differencial fluence of 0.01842 neutrons/second/m^2

################################################################################
## Geometry of the Source
## For horizontal drift detector geometry
################################################################################

################################################################################
## Source 1 - Side wall close to the detector
## Circle with area of 78.54 m^2
################################################################################

/gps/source/intensity 1.
##/gps/source/intensity 0.0052
/gps/particle neutron

/gps/ene/type Gauss
/gps/ene/mono 30. eV
/gps/ene/sigma 10. eV

/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/rot1 0 1 0
/gps/pos/rot2 1 0 0
/gps/pos/centre 0. 0. -2. m
/gps/pos/radius 5. m
/gps/ang/type iso
/gps/ang/maxtheta 45 deg
/gps/ang/mintheta -45 deg

################################################################################
## Source 2 - Floor
## Circle with area of 78.54 m^2 
################################################################################

/gps/source/add 1.
##/gps/source/add 0.0052
/gps/particle neutron

/gps/ene/type Gauss
/gps/ene/mono 30. eV
/gps/ene/sigma 10. eV

/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/rot1 0 0 1
/gps/pos/rot2 1 0 0
/gps/pos/centre 0. -3. 0. m
/gps/pos/radius 5. m
/gps/ang/type iso
/gps/ang/maxtheta 45 deg
/gps/ang/mintheta -45 deg

################################################################################
## Source 3 - Cave Ceiling
## Circle with area of 78.54 m^2 
################################################################################

/gps/source/add 1.
##/gps/source/add 0.0052
/gps/particle neutron

/gps/ene/type Gauss
/gps/ene/mono 30. eV
/gps/ene/sigma 10. eV

/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/rot1 0 0 1
/gps/pos/rot2 1 0 0
/gps/pos/centre 0. 10. 0. m
/gps/pos/radius 5. m
/gps/ang/type iso
/gps/ang/maxtheta 45 deg
/gps/ang/mintheta -45 deg

################################################################################
## Source 4 - Back of the cave, negligible contribution
## Circle with area of 314.16 m^2
################################################################################

#/gps/source/add 0.021
#/gps/particle neutron

#/gps/ene/type User
#/gps/hist/type energy
#/gps/hist/point 0. 0.0260712
#/gps/hist/point 0.2 0.0519149
#/gps/hist/point 0.4 0.0644695
#/gps/hist/point 0.6 0.0686237
#/gps/hist/point 0.8 0.0702712
#/gps/hist/point 1. 0.069995
#/gps/hist/point 1.2 0.0658463
#/gps/hist/point 1.4 0.0617589
#/gps/hist/point 1.6 0.0576174
#/gps/hist/point 1.8 0.0550852
#/gps/hist/point 2. 0.0501725
#/gps/hist/point 2.2 0.0460331
#/gps/hist/point 2.4 0.0426396
#/gps/hist/point 2.6 0.0374896
#/gps/hist/point 2.8 0.0339548
#/gps/hist/point 3. 0.0305741
#/gps/hist/point 3.2 0.0264008
#/gps/hist/point 3.4 0.0216205
#/gps/hist/point 3.6 0.0178012
#/gps/hist/point 3.8 0.0155747
#/gps/hist/point 4. 0.0128359
#/gps/hist/point 4.2 0.0110136
#/gps/hist/point 4.4 0.0094911
#/gps/hist/point 4.6 0.0082807
#/gps/hist/point 4.8 0.0072421
#/gps/hist/point 5. 0.0063383
#/gps/hist/point 5.2 0.0052699
#/gps/hist/point 5.4 0.0042666
#/gps/hist/point 5.6 0.0034948
#/gps/hist/point 5.8 0.0029247
#/gps/hist/point 6. 0.0025223
#/gps/hist/point 6.2 0.0020896
#/gps/hist/point 6.4 0.0017435
#/gps/hist/point 6.6 0.0014902
#/gps/hist/point 6.8 0.0013196
#/gps/hist/point 7. 0.0011781
#/gps/hist/point 7.2 0.0010319
#/gps/hist/point 7.4 0.0008613
#/gps/hist/point 7.6 0.0006678
#/gps/hist/point 7.8 0.0004972
#/gps/hist/point 8. 0.0004034
#/gps/hist/point 8.2 0.0003234
#/gps/hist/point 8.4 0.0002439
#/gps/hist/point 8.6 0.000184
#/gps/hist/point 8.8 0.0001439
#/gps/hist/point 9. 0.0001158
#/gps/hist/point 9.2 0.0000936

#/gps/pos/type Plane
#/gps/pos/shape Circle
#/gps/pos/rot1 0 1 0
#/gps/pos/rot2 0 0 1
#/gps/pos/centre -67. 0. 0. m
#/gps/pos/radius 10. m
#/gps/ang/type iso
#/gps/ang/maxtheta 45 deg
#/gps/ang/mintheta -45 deg

################################################################################
# Spherical source, for testing purposes
################################################################################

#/gps/pos/type Surface
#/gps/pos/shape Sphere
#/gps/pos/centre 0. 0. 0. m
#/gps/pos/radius 5. m
#/gps/ang/type iso
#/gps/ang/maxtheta 1 deg
#/gps/ang/mintheta 0 deg

# run
/run/beamOn 100000
