# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# configure marley
/Inputs/Particle_Type soup

# output path
/Inputs/root_output ../output/tmp.root

# initialize run
/run/initialize
/random/setSeeds 0 31

# limit radioactive decays
#/grdm/nucleusLimits 1 35 1 17  # aMin aMax zMin zMax
/grdm/nucleusLimits 1 39 1 19  # aMin aMax zMin zMax

# Supernova configs
/Supernova/Event_Window 10 s
/Supernova/N_Ar39_Decays 1000

# run
/run/beamOn 1

