# This is a comment and will be ignored by geant4

# The detector configuration (false  VD or true HD)
/geometry/use_hd_detector_configuration true

# World volume dimensions in meters. Place this config before run initialization
# For hd detectot geometry
/geometry/world_width  134.
/geometry/world_height 20.
/geometry/world_length 4.

# initialize run
/random/setSeeds 3981 31
/run/initialize

# Use this open statement to create an OpenGL view:
/vis/open OGL

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/viewpointThetaPhi 45 45 deg

# Specify zoom value:
/vis/viewer/zoom 1.0

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true

# set verbosity
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

# configure your generator for producing neutron background
/inputs/particle_type NEUTRON

# output path
/inputs/output_file ../output/neutron.root

# print eletrons from neutron capture. 0: false 1:true
/neutron/get_electrons 1

# run
/run/beamOn 1