# This is a comment and will be ignored by geant4

# The detector configuration (false  VD or true HD)
/geometry/use_hd_detector_configuration true

# World volume dimensions in meters. Place this config before run initialization
# For hd detector geometry
#/geometry/world_width  20.
#/geometry/world_height 20.
#/geometry/world_length 20.

/geometry/world_width  134.
/geometry/world_height 20.
/geometry/world_length 4.

# initialize run
/random/setSeeds 3981 31
/run/initialize

# set verbosity
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

# configure your generator for producing neutron background
/inputs/particle_type NEUTRON

# set verbosity on photons from neutron background
/neutron/nb_verbose 2

# output path
/inputs/output_file ../output/electron_NB.root

# print eletrons from neutron capture. 0: false 1:true
/neutron/get_electrons 1

# run
/run/beamOn 23332