# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# output path
/Inputs/root_output ./output/thorium228.root

# make unstable isotopes decay at t=0
/Inputs/decay_at_time_zero true  # this is set to false by default

# initialize run
/run/initialize
/random/setSeeds 0 31

# particle type
/gps/particle ion

# /gps/ion Z A Q E  # After /gps/particle ion, sets the properties (atomic
#                   # number Z, atomic mass A, ionic charge Q, excitation
#                   # energy E in keV) of the ion.

# /gps/ionLvl Z A Q lvl  # After /gps/particle ion, sets the properties
#                        # (atomic number Z, atomic mass A, ionic charge Q,
#                        # Number of metastable state excitation level (0-9)
#                        # of the ion.

# thorium-228
/gps/ion 90 228 0 0

# spherical volume source
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/centre 50. 50. 250. cm
/gps/pos/radius 25. cm

# energy distribution
/gps/ene/mono 1 eV

# run
/run/beamOn 5000
